### ISSUE TITLE
Getting error `res.getHeader is not a function`

### ISSUE THREAD

**Issue by rocketraman** [cvazac/express-middleware-server-timing#3]
When using this lib with express 4.x, I see:

```
{ TypeError: res.getHeader is not a function
    at appendHeader (/home/raman/source/test-timings/node_modules/express-middleware-server-timing/index.js:69:17)
    at Object.res.serverTimingStop [as end] (/home/raman/source/test-timings/node_modules/express-middleware-server-timing/index.js:33:9)
   ...
```

It seems you should pass `res` as the first parameter to the `appendHeader` call, rather than `this`.

**Comment by cvazac** [comment]
Inside `res.serverTimingStop`, `res` and `this` should be equivalent. How are you calling `serverTimingStop()`?

This works (for me):
```
app.get("/*", function(req, res, next) {
  res.serverTimingStart('name1')
  res.serverTimingStop('name1')
  // ...
})
```

This does/will **not** work:
```
app.get("/*", function(req, res, next) {
  res.serverTimingStart('name2')
  var stop = res.serverTimingStop
  stop('name2')
  // ...
}
```

**Comment by rocketraman** [comment]
I don't recall honestly... I believe I was just calling the functions normally, but I had some type of delegation somewhere in my code so I believe the usage would have been like your second example. I forked your project and changed the method to pass `res` and that fixed the problem for me. I think that is a safer approach than relying on `this`.

**Comment by cvazac** [comment]
feel free to reopen if you can reproduce, thanks!
