### ISSUE TITLE
Library is too invasive

### ISSUE THREAD

**Issue by rocketraman** [cvazac/express-middleware-server-timing#4]
This library takes over my `listen` function. This isn't very good separation of concerns -- I don't want a middleware taking over a core function.

You should support a mode of operation in which users can just get the middleware function you create, and inject it themselves into their app.

**Comment by cvazac** [comment]
The reason why I [hijack](https://github.com/cvazac/express-middleware-server-timing/blob/master/index.js#L9) and then [delegate](https://github.com/cvazac/express-middleware-server-timing/blob/master/index.js#L52) to the `listen` method is to guarantee my middleware run **first**. To me, it makes the usage (almost) impossible to get wrong - all you have to do is `require('express-middleware-server-timing')` _before_ `app.listen(...)`.

YMMV

I agree that a "manual" mode is a good idea.

**Comment by rocketraman** [comment]
> The reason why I hijack and then delegate to the listen method is to guarantee my middleware run first. To me, it makes the usage (almost) impossible to get wrong - all you have to do is require('express-middleware-server-timing') before app.listen(...).

It is foolproof, yes. I'm not a fool :-)

> YMMV

In my case, I use the return value of `listen`, which is a `server`, and do stuff with it, including operations based on process signals. So the hijack approach works well when the user has a very simple app, but as soon as one needs to do something a little more complex the timing middleware is no longer a "good citizen".

**Comment by cvazac** [comment]
huge mistake on my part to not pass on the return value, thanks for finding. fixed as of: 3.0.1
